/*******************************************************************************
 * DISCLAIMER
 * This software is supplied by Renesas Electronics Corporation and is only
 * intended for use with Renesas products. No other uses are authorized. This
 * software is owned by Renesas Electronics Corporation and is protected under
 * all applicable laws, including copyright laws.
 * THIS SOFTWARE IS PROVIDED "AS IS" AND RENESAS MAKES NO WARRANTIES REGARDING
 * THIS SOFTWARE, WHETHER EXPRESS, IMPLIED OR STATUTORY, INCLUDING BUT NOT
 * LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE
 * AND NON-INFRINGEMENT. ALL SUCH WARRANTIES ARE EXPRESSLY DISCLAIMED.
 * TO THE MAXIMUM EXTENT PERMITTED NOT PROHIBITED BY LAW, NEITHER RENESAS
 * ELECTRONICS CORPORATION NOR ANY OF ITS AFFILIATED COMPANIES SHALL BE LIABLE
 * FOR ANY DIRECT, INDIRECT, SPECIAL, INCIDENTAL OR CONSEQUENTIAL DAMAGES FOR
 * ANY REASON RELATED TO THIS SOFTWARE, EVEN IF RENESAS OR ITS AFFILIATES HAVE
 * BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.
 * Renesas reserves the right, without notice, to make changes to this software
 * and to discontinue the availability of this software. By using this software,
 * you agree to the additional terms and conditions found by accessing the
 * following link:
 * http://www.renesas.com/disclaimer
 * (C) 2012-2017 Renesas Electronics Corporation All rights reserved.
 ******************************************************************************/

/******************************************************************************
 * File Name  : rble_sample_app_peripheral.c
 * Version    : 1.0
 * Description: sample application peripheral role source file
 *
 * Copyright(C) 2013-2017 Renesas Electronics Corporation
 *
 * This file is generated by Bluetooth Developer Studio plugin.
 *     BDS Version    : 1.1.3139.0
 *     Script Version : 2.0.1
 *
 ******************************************************************************/

/*******************************************************************************
 * Include Files
 ******************************************************************************/
#include "rble_sample_app_peripheral.h"
#include "console.h"
#include "sam/sams.h"
#include "led_onoff.h"
#include "push_state.h"
#include "push_sw.h"
#include "r_cg_userdefine.h"
#include "QTask.h"
#include "QUtils.h"
#include "dataflash.h"
#include "eel_descriptor_t02.h"
#include "QFlash.h"
/*******************************************************************************
 * Macro Definitions
 ******************************************************************************/
#define APP_SWITCH_STATE_CHECK_INTERVAL (50)

/*******************************************************************************
 * Function Declarations
 ******************************************************************************/
static void app_msg_send(ke_msg_id_t id);
static int_t app_reset(ke_msg_id_t const msgid, void const *param,
                       ke_task_id_t const dest_id, ke_task_id_t const src_id);
static int_t app_advertise_start(ke_msg_id_t const msgid, void const *param,
                                 ke_task_id_t const dest_id, ke_task_id_t const src_id);
static int_t app_profile_enable(ke_msg_id_t const msgid, void const *param,
                                ke_task_id_t const dest_id, ke_task_id_t const src_id);
static int_t app_profile_disable(ke_msg_id_t const msgid, void const *param,
                                 ke_task_id_t const dest_id, ke_task_id_t const src_id);
static int_t app_timer_expired(ke_msg_id_t const msgid, void const *param,
                               ke_task_id_t const dest_id, ke_task_id_t const src_id);

static void app_gap_callback(RBLE_GAP_EVENT *event);
static void app_sams_callback(NEW_PROFILE_SERVER_EVENT *event);

static void app_sm_callback(RBLE_SM_EVENT *event);

/*******************************************************************************
 * Global Variables
 ******************************************************************************/
SET_DATA_INFO ADV_Data;
 
RBLE_BD_NAME bd_name_param = {
    sizeof( "Quan-Beacon-" ),   /*length for name */
    "Quan-Beacon-"              /* array of bytes for name */
};

RBLE_BD_NAME bd_name_param_flash = {
    0,   /*length for name */
    ""              /* array of bytes for name */
};
 
static struct {
    uint16_t conhdl;
} app_info;

/* ##### Task Definitions ##### */
ke_state_t app_state[APP_IDX_MAX];

const struct ke_msg_handler app_reset_handler[] = {
    { APP_MSG_BOOTUP,        (ke_msg_func_t)app_reset },
};

const struct ke_msg_handler app_nonconnect_handler[] = {
    { APP_MSG_RESET_COMP,            (ke_msg_func_t)app_advertise_start },
    { APP_MSG_DISCONNECTED,          (ke_msg_func_t)app_profile_disable },
    { APP_MSG_PROFILE_DISABLED,      (ke_msg_func_t)app_advertise_start },
};

const struct ke_msg_handler app_connect_handler[] = {
    { APP_MSG_CONNECTED,       (ke_msg_func_t)app_profile_enable },
    /* { APP_MSG_PROFILE_ENABLED, (ke_msg_func_t)NULL }, */
    { APP_MSG_TIMER_EXPIRED,   (ke_msg_func_t)app_timer_expired },
};

const struct ke_state_handler app_state_handler[APP_STATE_MAX] =
{
    KE_STATE_HANDLER(app_reset_handler),
    KE_STATE_HANDLER(app_nonconnect_handler),
    KE_STATE_HANDLER(app_connect_handler),
};

/* ##### Advertise Parameter ##### */
static RBLE_ADV_INFO app_advertise_param = {
	0x64, 0xFF, 						/* advertising interval ( msec = param * 0.625msec ) Range:0x0020-0x4000 */
    RBLE_GAP_ADV_CONN_UNDIR,            /* advertising channel PDU type */
    RBLE_ADDR_PUBLIC,                   /* own bluetooth address type */
    RBLE_ADDR_PUBLIC,                   /* peer bluetooth address type */
    { 0x0 },                            /* not used */
	RBLE_ADV_ALL_CHANNELS,				/* advertising channel */
	RBLE_ADV_ALLOW_SCAN_ANY_CON_ANY,	/* advertising policy */
    0x00,                               /* reserved */
    {                                   /* advertising data */
		/* AdvDataLen */
		20,
		/* AdvData */
		0x02, 0x01, 0x06,		/* Flags ( LE General Discoverable Mode | BR/EDR Not Supported ) */
		0x03, 0x03, 0x00, 0xbb, /* Complete List of 16-bit Service Class UUIDs */
		0x0C, 0x09, 'Q', 'u', 'a', 'n', '-', 'B', 'e', 'a', 'c', 'o', 'n',  /* Complete local name */
		0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
    }
};

RBLE_ADV_INFO  Eddystone_Temp  =
{	
    {
        0x00A0,  /* 100msec (0xA0 * 625usec) */     /* AdvIntervalMin */
        0x00A0,                                     /* AdvIntervalMax */
        RBLE_GAP_ADV_DISC_UNDIR,                    /* AdvType        */
        RBLE_ADDR_PUBLIC,                           /* OwnAddrType    */
        RBLE_ADDR_PUBLIC,                           /* DirectAddrType */
        { 0x00, 0x00, 0x00, 0x00, 0x00, 0x00 },     /* DirectAddr     */
        RBLE_ADV_ALL_CHANNELS,                      /* AdvChannelMap  */
        RBLE_ADV_ALLOW_SCAN_ANY_CON_ANY,            /* AdvFiltPolicy  */
        0x00,                                       /* Reserved       */
    },
    {
00
    }
};

RBLE_ADV_INFO  Eddystone_UID  =
{
    {
        0x00A0,  /* 100msec (0xA0 * 625usec) */     /* AdvIntervalMin */
        0x00A0,                                     /* AdvIntervalMax */
        RBLE_GAP_ADV_DISC_UNDIR,                    /* AdvType        */
        RBLE_ADDR_PUBLIC,                           /* OwnAddrType    */
        RBLE_ADDR_PUBLIC,                           /* DirectAddrType */
        { 0x00, 0x00, 0x00, 0x00, 0x00, 0x00 },     /* DirectAddr     */
        RBLE_ADV_ALL_CHANNELS,                      /* AdvChannelMap  */
        RBLE_ADV_ALLOW_SCAN_ANY_CON_ANY,            /* AdvFiltPolicy  */
        0x00,                                       /* Reserved       */
    },
    {
        /* AdvDataLen     */
        31,
        /* AdvData        */
       	0x02, 0x01, 0x06, /* Flags */ 
	
	0x03, 0x03, 0xAA, 0xFE, /* Complete List of 16-bit Service Class UUIDs */
	
	0x17,   //len
	0x16,
	0xAA,0xFE,
	
        0x00, /*fram Type */
	
	0xBF, /*1M power */
	
	0xe2,0xc5,0x6d,0xb5,0xdf,0xfb,0x48,0xd2,0xb0,0x60, //NID
	0xd0,0xf5,0xa7,0xe0,0x96,0xe0, //BID
	0x00,0x00
    }
};

RBLE_ADV_INFO  Eddystone_UID_N_flash  =
{
    {
        0x00A0,  /* 100msec (0xA0 * 625usec) */     /* AdvIntervalMin */
        0x00A0,                                     /* AdvIntervalMax */
        RBLE_GAP_ADV_DISC_UNDIR,                    /* AdvType        */
        RBLE_ADDR_PUBLIC,                           /* OwnAddrType    */
        RBLE_ADDR_PUBLIC,                           /* DirectAddrType */
        { 0x00, 0x00, 0x00, 0x00, 0x00, 0x00 },     /* DirectAddr     */
        RBLE_ADV_ALL_CHANNELS,                      /* AdvChannelMap  */
        RBLE_ADV_ALLOW_SCAN_ANY_CON_ANY,            /* AdvFiltPolicy  */
        0x00,                                       /* Reserved       */
    },
    {
        /* AdvDataLen     */
        31,
        /* AdvData        */
       	0x02, 0x01, 0x06, /* Flags */ 
	
	0x03, 0x03, 0xAA, 0xFE, /* Complete List of 16-bit Service Class UUIDs */
	
	0x17,   //len
	0x16,
	0xAA,0xFE,
	
        0x00, /*fram Type */
	
	0xBF, /*1M power */
	
	0x12,0x34,0x56,0xb5,0xdf,0xfb,0x48,0xd2,0xb0,0x60, //NID
	0xd0,0xf5,0xa7,0xe0,0x96,0xe0, //BID
	0x00,0x00
    }
};

RBLE_ADV_INFO  Eddystone_UID_L_flash  =
{
    {
        0x00A0,  /* 100msec (0xA0 * 625usec) */     /* AdvIntervalMin */
        0x00A0,                                     /* AdvIntervalMax */
        RBLE_GAP_ADV_DISC_UNDIR,                    /* AdvType        */
        RBLE_ADDR_PUBLIC,                           /* OwnAddrType    */
        RBLE_ADDR_PUBLIC,                           /* DirectAddrType */
        { 0x00, 0x00, 0x00, 0x00, 0x00, 0x00 },     /* DirectAddr     */
        RBLE_ADV_ALL_CHANNELS,                      /* AdvChannelMap  */
        RBLE_ADV_ALLOW_SCAN_ANY_CON_ANY,            /* AdvFiltPolicy  */
        0x00,                                       /* Reserved       */
    },
    {
        /* AdvDataLen     */
        31,
        /* AdvData        */
       	0x02, 0x01, 0x06, /* Flags */ 
	
	0x03, 0x03, 0xAA, 0xFE, /* Complete List of 16-bit Service Class UUIDs */
	
	0x17,   //len
	0x16,
	0xAA,0xFE,
	
        0x00, /*fram Type */
	
	0xBF, /*1M power */
	
	0x12,0x34,0x56,0xb5,0xdf,0xfb,0x48,0xd2,0xb0,0x60, //NID
	0xd0,0xf5,0xa7,0xe0,0x96,0xe1, //BID
	0x00,0x00
    }
};

RBLE_ADV_INFO  Eddystone_UID_R_flash  =
{
    {
        0x00A0,  /* 100msec (0xA0 * 625usec) */     /* AdvIntervalMin */
        0x00A0,                                     /* AdvIntervalMax */
        RBLE_GAP_ADV_DISC_UNDIR,                    /* AdvType        */
        RBLE_ADDR_PUBLIC,                           /* OwnAddrType    */
        RBLE_ADDR_PUBLIC,                           /* DirectAddrType */
        { 0x00, 0x00, 0x00, 0x00, 0x00, 0x00 },     /* DirectAddr     */
        RBLE_ADV_ALL_CHANNELS,                      /* AdvChannelMap  */
        RBLE_ADV_ALLOW_SCAN_ANY_CON_ANY,            /* AdvFiltPolicy  */
        0x00,                                       /* Reserved       */
    },
    {
        /* AdvDataLen     */
        31,
        /* AdvData        */
       	0x02, 0x01, 0x06, /* Flags */ 
	
	0x03, 0x03, 0xAA, 0xFE, /* Complete List of 16-bit Service Class UUIDs */
	
	0x17,   //len
	0x16,
	0xAA,0xFE,
	
        0x00, /*fram Type */
	
	0xBF, /*1M power */
	
	0x12,0x34,0x56,0xb5,0xdf,0xfb,0x48,0xd2,0xb0,0x60, //NID
	0xd0,0xf5,0xa7,0xe0,0x96,0xe2, //BID
	0x00,0x00
    }
};

RBLE_ADV_INFO  Eddystone_URL=
{
    {
        0x00A0,  /* 100msec (0xA0 * 625usec) */     /* AdvIntervalMin */
        0x00A0,                                     /* AdvIntervalMax */
        RBLE_GAP_ADV_DISC_UNDIR,                    /* AdvType        */
        RBLE_ADDR_PUBLIC,                           /* OwnAddrType    */
        RBLE_ADDR_PUBLIC,                           /* DirectAddrType */
        { 0x00, 0x00, 0x00, 0x00, 0x00, 0x00 },     /* DirectAddr     */
        RBLE_ADV_ALL_CHANNELS,                      /* AdvChannelMap  */
        RBLE_ADV_ALLOW_SCAN_ANY_CON_ANY,            /* AdvFiltPolicy  */
        0x00,                                       /* Reserved       */
    },
    {
        /* AdvDataLen     */
        31,
        /* AdvData        */
       	0x02, 0x01, 0x06, /* Flags */ 
	
	0x03, 0x03, 0xAA, 0xFE, /* Complete List of 16-bit Service Class UUIDs */
	
	0x13,   //len
	0x16,
	0xAA,0xFE,
	
        0x10, /*fram Type */
	
	0xBF, /*1M power */
	
 	0x01,
        'p', 'c', 'h', 'o', 'm', 'e', 0x07,'.','t','w'
    }
};
RBLE_ADV_INFO Eddystone_URL_N_flash=
{
    {
        0x00A0,  /* 100msec (0xA0 * 625usec) */     /* AdvIntervalMin */
        0x00A0,                                     /* AdvIntervalMax */
        RBLE_GAP_ADV_DISC_UNDIR,                    /* AdvType        */
        RBLE_ADDR_PUBLIC,                           /* OwnAddrType    */
        RBLE_ADDR_PUBLIC,                           /* DirectAddrType */
        { 0x01, 0x02, 0x03, 0x04, 0x05, 0x06 },     /* DirectAddr     */
        RBLE_ADV_ALL_CHANNELS,                      /* AdvChannelMap  */
        RBLE_ADV_ALLOW_SCAN_ANY_CON_ANY,            /* AdvFiltPolicy  */
        0x00,                                       /* Reserved       */
    },
    {
        /* AdvDataLen     */
        31,
        /* AdvData        */
       	0x02, 0x01, 0x06, /* Flags */ 
	
	0x03, 0x03, 0xAA, 0xFE, /* Complete List of 16-bit Service Class UUIDs */
	
	0x13,   //len
	0x16,
	0xAA,0xFE,
	
        0x10, /*fram Type */
	
	0xBF, /*1M power */
	
 	0x02,
        'g', 'o', 'o', '.', 'g', 'l', '/', '5', 'w', 'K', 'k', 'R', 'K'
    }
};

RBLE_ADV_INFO Eddystone_URL_L_flash=
{
    {
        0x00A0,  /* 100msec (0xA0 * 625usec) */     /* AdvIntervalMin */
        0x00A0,                                     /* AdvIntervalMax */
        RBLE_GAP_ADV_DISC_UNDIR,                    /* AdvType        */
        RBLE_ADDR_PUBLIC,                           /* OwnAddrType    */
        RBLE_ADDR_PUBLIC,                           /* DirectAddrType */
        { 0x01, 0x02, 0x03, 0x04, 0x05, 0x06 },     /* DirectAddr     */
        RBLE_ADV_ALL_CHANNELS,                      /* AdvChannelMap  */
        RBLE_ADV_ALLOW_SCAN_ANY_CON_ANY,            /* AdvFiltPolicy  */
        0x00,                                       /* Reserved       */
    },
    {
        /* AdvDataLen     */
        31,
        /* AdvData        */
       	0x02, 0x01, 0x06, /* Flags */ 
	
	0x03, 0x03, 0xAA, 0xFE, /* Complete List of 16-bit Service Class UUIDs */
	
	0x0C,   //len
	0x16,
	0xAA,0xFE,
	
        0x10, /*fram Type */
	
	0xBF, /*1M power */
	
 	0x01,
        'y', 'a', 'h', 'o', 'o', 0x07
    }
};

RBLE_ADV_INFO Eddystone_URL_R_flash=
{
    {
        0x00A0,  /* 100msec (0xA0 * 625usec) */     /* AdvIntervalMin */
        0x00A0,                                     /* AdvIntervalMax */
        RBLE_GAP_ADV_DISC_UNDIR,                    /* AdvType        */
        RBLE_ADDR_PUBLIC,                           /* OwnAddrType    */
        RBLE_ADDR_PUBLIC,                           /* DirectAddrType */
        { 0x01, 0x02, 0x03, 0x04, 0x05, 0x06 },     /* DirectAddr     */
        RBLE_ADV_ALL_CHANNELS,                      /* AdvChannelMap  */
        RBLE_ADV_ALLOW_SCAN_ANY_CON_ANY,            /* AdvFiltPolicy  */
        0x00,                                       /* Reserved       */
    },
    {
        /* AdvDataLen     */
        31,
        /* AdvData        */
       	0x02, 0x01, 0x06, /* Flags */ 
	
	0x03, 0x03, 0xAA, 0xFE, /* Complete List of 16-bit Service Class UUIDs */
	
	0x13,   //len
	0x16,
	0xAA,0xFE,
	
        0x10, /*fram Type */
	
	0xBF, /*1M power */
	
 	0x01,
        'g', 'o', 'o', 'g', 'l', 'e', 0x07
    }
};

const RBLE_ADV_INFO  Eddystone_TLM  =
{
    {
        0x00A0,  /* 100msec (0xA0 * 625usec) */     /* AdvIntervalMin */
        0x00A0,                                     /* AdvIntervalMax */
        RBLE_GAP_ADV_DISC_UNDIR,                    /* AdvType        */
        RBLE_ADDR_PUBLIC,                           /* OwnAddrType    */
        RBLE_ADDR_PUBLIC,                           /* DirectAddrType */
        { 0x00, 0x00, 0x00, 0x00, 0x00, 0x00 },     /* DirectAddr     */
        RBLE_ADV_ALL_CHANNELS,                      /* AdvChannelMap  */
        RBLE_ADV_ALLOW_SCAN_ANY_CON_ANY,            /* AdvFiltPolicy  */
        0x00,                                       /* Reserved       */
    },
    {
        /* AdvDataLen     */
        31,
        /* AdvData        */
       	0x02, 0x01, 0x06, /* Flags */ 
	
	0x03, 0x03, 0xAA, 0xFE, /* Complete List of 16-bit Service Class UUIDs */
	
	0x17,   //len
	0x16,
	0xAA,0xFE,
	
        0x20, /*fram Type */
	
	0x00, /*TLM V */
	
	0x10,0x01,  //Battery
	0x00,0x00,  //Temperature
	0xdf,0xfb,0x48,0xd2,//PDU
	0xb0,0x60,0xd0,0xf5,  //ADV COUNT
	0x00,0x00,0x00,0x00, //POWER on
	0x00,0x00
    }
};

const struct ke_state_handler app_default_handler = KE_STATE_HANDLER_NONE;
NEW_PROFILE_SERVER_PARAM samps_param = { 0xffff };

/*LED*/
extern uint8_t LEDChoose;
/* Data_mode*/
Setup_Data_t Default;
Setup_Data_t Normal;
Setup_Data_t Left;
Setup_Data_t Right;
Setup_Data_t RamTemp;

Setup_ALLData_t ALLData;
Setup_ALLData_t ALLDataTemp;
/*Profile_Mode*/
Profile_Mode_t Profile;
/*ADV_Scr*/
/*
ADV_Data_t Left_ADV;
ADV_Data_t Temp_ADV;
*/

uint16_t RamADV_Interval=0;
uint8_t RamADV_Count=0;
uint8_t RamUID_Count=0;
uint8_t RamURL_Count=0;
ADV_Data_t Ram_ADV;
/*
ADV_Data_t Ram_URL_ADV;
ADV_Data_t Ram_TLM_ADV;
*/
/*******************************************************************************
 * Function Definitions (Internal)
 ******************************************************************************/
/* ##### Message Handler ##### */
static void app_msg_send(ke_msg_id_t id)
{
    /* Send blank msg to itself. The content is shared through
       app_info global variable. */
    ke_msg_send_basic(id, APP_TASK_ID, APP_TASK_ID);
}


static int_t app_reset(ke_msg_id_t const msgid, void const *param,
                       ke_task_id_t const dest_id, ke_task_id_t const src_id)
{
    (void)led_onoff_init(R_LED4);
    //(void)push_state_init(R_SW4);
    (void)push_sw2_start(0);
    
    (void)push_sw1_start(0);
    (void)RBLE_GAP_Reset(&app_gap_callback, &app_sm_callback);

    return KE_MSG_CONSUMED;
}

static int_t app_advertise_start(ke_msg_id_t const msgid, void const *param,
                                 ke_task_id_t const dest_id, ke_task_id_t const src_id)
{
	/*
    (void)RBLE_GAP_Broadcast_Enable(
        RBLE_GAP_GEN_DISCOVERABLE, RBLE_GAP_UND_CONNECTABLE,
        &Eddystone_UID);
*/
    APP_Set_RunCmd(UID_Change);
    return KE_MSG_CONSUMED;
}

static int_t app_profile_enable(ke_msg_id_t const msgid, void const *param,
                                ke_task_id_t const dest_id, ke_task_id_t const src_id)
{
    (void)NEW_PROFILE_Server_Enable(app_info.conhdl, RBLE_PRF_CON_DISCOVERY,
                               &samps_param, &app_sams_callback);

    return KE_MSG_CONSUMED;
}

static int_t app_profile_disable(ke_msg_id_t const msgid, void const *param,
                                 ke_task_id_t const dest_id, ke_task_id_t const src_id)
{
    (void)NEW_PROFILE_Server_Disable(app_info.conhdl);

    return KE_MSG_CONSUMED;
}

static int_t app_timer_expired(ke_msg_id_t const msgid, void const *param,
                               ke_task_id_t const dest_id, ke_task_id_t const src_id)
{

    return KE_MSG_CONSUMED;
}

/* ##### GAP Event Handler ##### */
void app_gap_callback(RBLE_GAP_EVENT *event)
{
    switch (event->type) {
    case RBLE_GAP_EVENT_RESET_RESULT:
        ke_state_set(APP_TASK_ID, APP_NONCONNECT_STATE);
        app_msg_send(APP_MSG_RESET_COMP);
        break;

    case RBLE_GAP_EVENT_BROADCAST_ENABLE_COMP:
    case RBLE_GAP_EVENT_BROADCAST_DISABLE_COMP:
        /* do nothing */
        break;

    case RBLE_GAP_EVENT_CONNECTION_COMP:
        if (RBLE_OK == event->param.status) {
            app_info.conhdl = event->param.conn_comp.connect_info.conhdl;
            ke_state_set(APP_TASK_ID, APP_CONNECT_STATE);
            app_msg_send(APP_MSG_CONNECTED);
        } else {
            ke_state_set(APP_TASK_ID, APP_NONCONNECT_STATE);
            app_msg_send(APP_MSG_DISCONNECTED);
        }
        break;

    case RBLE_GAP_EVENT_DISCONNECT_COMP:
        ke_state_set(APP_TASK_ID, APP_NONCONNECT_STATE);
        app_msg_send(APP_MSG_DISCONNECTED);
        break;

    default:
        Printf("unsupported GAP event: 0x%x\n", event->type);
        break;
    }
}

/* ##### SM Event Handler ##### */
void app_sm_callback(RBLE_SM_EVENT *event)
{
    Printf("unsupported event: 0x%x\n", event->type);
}

/* ##### Sample Custom Profile Handler ##### */
void app_sams_callback(NEW_PROFILE_SERVER_EVENT *event)
{
    uint8_t CMD_Temp[20]={0};
    uint8_t Null_Temp[65]={0};
    uint8_t CMD_Data_len=0;
    
    switch (event->type) {
    case NEW_PROFILE_SERVER_EVENT_ENABLE_COMP:
        app_msg_send(APP_MSG_PROFILE_ENABLED);
        break;

    case NEW_PROFILE_SERVER_EVENT_DISABLE_COMP:
        app_msg_send(APP_MSG_PROFILE_DISABLED);
        break;

    case NEW_PROFILE_SERVER_EVENT_SET_VALUE_COMP:
        break;

    case NEW_PROFILE_SERVER_EVENT_CHAR_WRITE_RESP:
    
	if((event->param.char_write_resp_evt.bs_cmd_char_val_len)!=0){
	    memcpy(CMD_Temp,event->param.char_write_resp_evt.char_write_resp_evt_val.bs_cmd_char_val,event->param.char_write_resp_evt.bs_cmd_char_val_len);  //catch CMD head
	    CMD_Data_len=event->param.char_write_resp_evt.bs_cmd_char_val_len-1;
	    switch(CMD_Temp[0]){   //CMD Number
	        case 1:    //ADV NAME
		    memcpy(CMD_Temp,&event->param.char_write_resp_evt.char_write_resp_evt_val.bs_cmd_char_val[1],event->param.char_write_resp_evt.bs_cmd_char_val_len-1);
		    bd_name_param.namelen=event->param.char_write_resp_evt.bs_cmd_char_val_len-1;
		    memcpy(bd_name_param.name,Null_Temp,65);  //erease
		    memcpy(bd_name_param.name,CMD_Temp,event->param.char_write_resp_evt.bs_cmd_char_val_len-1);
		
		   // Write_Data_flash(&bd_name_param,EEL_ID_ADV);   //push data to flash

	        break;
		
	        case 2:    //N_UID
	           memcpy(&Eddystone_UID_N_flash.adv_data.adv_data.data[13],Null_Temp,17);
		   memcpy(CMD_Temp,&event->param.char_write_resp_evt.char_write_resp_evt_val.bs_cmd_char_val[1],event->param.char_write_resp_evt.bs_cmd_char_val_len-1);
		   Eddystone_UID_N_flash.adv_data.adv_data.data[7]=CMD_Data_len+5;    //URL ADV len
		   
		   memcpy(&Eddystone_UID_N_flash.adv_data.adv_data.data[13],CMD_Temp,CMD_Data_len);
		   
		   memcpy(Eddystone_Temp.adv_data.adv_data.data,Null_Temp,31);
 	
		   memcpy(Eddystone_Temp.adv_data.adv_data.data,Eddystone_UID_N_flash.adv_data.adv_data.data,31);

		   Write_Data_flash(&Eddystone_UID_N_flash,EEL_ID_NUID);   //push data to flash
	
	        break;
		
	        case 3:    //L_UID
	           memcpy(&Eddystone_UID_L_flash.adv_data.adv_data.data[13],Null_Temp,17);
		   memcpy(CMD_Temp,&event->param.char_write_resp_evt.char_write_resp_evt_val.bs_cmd_char_val[1],event->param.char_write_resp_evt.bs_cmd_char_val_len-1);
		   Eddystone_UID_L_flash.adv_data.adv_data.data[7]=CMD_Data_len+5;    //URL ADV len
		   
		   memcpy(&Eddystone_UID_L_flash.adv_data.adv_data.data[13],CMD_Temp,CMD_Data_len);
		   
		   memcpy(Eddystone_Temp.adv_data.adv_data.data,Null_Temp,31);
 	
		   memcpy(Eddystone_Temp.adv_data.adv_data.data,Eddystone_UID_L_flash.adv_data.adv_data.data,31);

		   Write_Data_flash(&Eddystone_UID_L_flash,EEL_ID_LUID);   //push data to flash
	
	        break;
		
	        case 4:    //R_UID
	           memcpy(&Eddystone_UID_R_flash.adv_data.adv_data.data[13],Null_Temp,17);
		   memcpy(CMD_Temp,&event->param.char_write_resp_evt.char_write_resp_evt_val.bs_cmd_char_val[1],event->param.char_write_resp_evt.bs_cmd_char_val_len-1);
		   Eddystone_UID_R_flash.adv_data.adv_data.data[7]=CMD_Data_len+5;    //URL ADV len
		   
		   memcpy(&Eddystone_UID_R_flash.adv_data.adv_data.data[13],CMD_Temp,CMD_Data_len);
		   
		   memcpy(Eddystone_Temp.adv_data.adv_data.data,Null_Temp,31);
 	
		   memcpy(Eddystone_Temp.adv_data.adv_data.data,Eddystone_UID_R_flash.adv_data.adv_data.data,31);

		   Write_Data_flash(&Eddystone_UID_R_flash,EEL_ID_RUID);   //push data to flash
	        break;
		
	        case 5:    //N_URL
	           memcpy(&Eddystone_URL_N_flash.adv_data.adv_data.data[13],Null_Temp,17);
		   memcpy(CMD_Temp,&event->param.char_write_resp_evt.char_write_resp_evt_val.bs_cmd_char_val[1],event->param.char_write_resp_evt.bs_cmd_char_val_len-1);
		   Eddystone_URL_N_flash.adv_data.adv_data.data[7]=CMD_Data_len+5;    //URL ADV len
		   
		   memcpy(&Eddystone_URL_N_flash.adv_data.adv_data.data[13],CMD_Temp,CMD_Data_len);
		   
		   memcpy(Eddystone_Temp.adv_data.adv_data.data,Null_Temp,31);
 	
		   memcpy(Eddystone_Temp.adv_data.adv_data.data,Eddystone_URL_N_flash.adv_data.adv_data.data,31);

		      
		  //APP_Set_RunCmd(APP_ADV_Update);
		    Write_Data_flash(&Eddystone_URL_N_flash,EEL_ID_NURL);   //push data to flash
	        break;	
		
	        case 6:    //L_URL
	           memcpy(&Eddystone_URL_L_flash.adv_data.adv_data.data[13],Null_Temp,17);
		   memcpy(CMD_Temp,&event->param.char_write_resp_evt.char_write_resp_evt_val.bs_cmd_char_val[1],event->param.char_write_resp_evt.bs_cmd_char_val_len-1);
		   Eddystone_URL_L_flash.adv_data.adv_data.data[7]=CMD_Data_len+5;    //URL ADV len
		   
		   memcpy(&Eddystone_URL_L_flash.adv_data.adv_data.data[13],CMD_Temp,CMD_Data_len);
		   
		   memcpy(Eddystone_Temp.adv_data.adv_data.data,Null_Temp,31);
 	
		   memcpy(Eddystone_Temp.adv_data.adv_data.data,Eddystone_URL_L_flash.adv_data.adv_data.data,31);

		      
		  //APP_Set_RunCmd(APP_ADV_Update);
		    Write_Data_flash(&Eddystone_URL_L_flash,EEL_ID_LURL);   //push data to flash
	        break;
		
	        case 7:    //R_URL
	           memcpy(&Eddystone_URL_R_flash.adv_data.adv_data.data[13],Null_Temp,17);
		   memcpy(CMD_Temp,&event->param.char_write_resp_evt.char_write_resp_evt_val.bs_cmd_char_val[1],event->param.char_write_resp_evt.bs_cmd_char_val_len-1);
		   Eddystone_URL_R_flash.adv_data.adv_data.data[7]=CMD_Data_len+5;    //URL ADV len
		   
		   memcpy(&Eddystone_URL_R_flash.adv_data.adv_data.data[13],CMD_Temp,CMD_Data_len);
		   
		   memcpy(Eddystone_Temp.adv_data.adv_data.data,Null_Temp,31);
 	
		   memcpy(Eddystone_Temp.adv_data.adv_data.data,Eddystone_URL_R_flash.adv_data.adv_data.data,31);

		      
		  //APP_Set_RunCmd(APP_ADV_Update);
		    Write_Data_flash(&Eddystone_URL_R_flash,EEL_ID_RURL);   //push data to flash
	        break;
		
		case 8:    //Reste
		    dataflash_format(DF_MODE_ENFORCED);
	        break;
		
		case 9:    //Buzzer_On_Off
	            if(CMD_Temp[1]!=0){
			Buzzer_Count=CMD_Temp[1];
		    }
		
	            if(CMD_Temp[1]==1){
			G1D_Sleep_flag=true;
			Buzzer_Count_Temp=Buzzer_Count;
			APP_Set_RunCmd(APP_Buzzer_ON);
		    }else{
			G1D_Sleep_flag=false;
			APP_Set_RunCmd(APP_Buzzer_OFF);
		    }
		    
		    
	        break;
		    
		case 10:    //ADV_Interval 
		    Default.Adv_Interval=CMD_Temp[1];
		    Normal.Adv_Interval=CMD_Temp[2];
		    Left.Adv_Interval=CMD_Temp[3];
		    Right.Adv_Interval=CMD_Temp[4];

		    memcpy(&ALLData.Default2,&Default,17);
		    memcpy(&ALLData.Normal2,&Normal,17);
		    memcpy(&ALLData.Left2,&Left,17);
		    memcpy(&ALLData.Right2,&Right,17);
		    
		    Write_Data_flash(&ALLData,EEL_ID_ALL_Seting);   //push data to flash
		
		/*
	            if(CMD_Temp[1]!=0){
		        ButtSet.Right_Button=CMD_Temp[1];
			ButtSet.Left_Button=0;
			ButtSet.Mark=0x88;
		       // Write_Data_flash(&ButtSet,EEL_ID_Switch);   //push data to flash
		    }
		    */
	        break;
		case 11:    //UID_Count
		    Default.UID_Count=CMD_Temp[1];
		    Normal.UID_Count=CMD_Temp[2];
		    Left.UID_Count=CMD_Temp[3];
		    Right.UID_Count=CMD_Temp[4];

		    memcpy(&ALLData.Default2,&Default,17);
		    memcpy(&ALLData.Normal2,&Normal,17);
		    memcpy(&ALLData.Left2,&Left,17);
		    memcpy(&ALLData.Right2,&Right,17);
		    
		    Write_Data_flash(&ALLData,EEL_ID_ALL_Seting);   //push data to flash
		
		
		
/*
	            if(CMD_Temp[1]!=0){
		        ButtSet.Left_Button=CMD_Temp[1];
			ButtSet.Right_Button=0;
			ButtSet.Mark=0x88;
		       // Write_Data_flash(&ButtSet,EEL_ID_Switch);   //push data to flash
		    }
		    */
	        break;
		
		case 12:    //URL_Count 
		
		
		    Default.URL_Count=CMD_Temp[1];
		    Normal.URL_Count=CMD_Temp[2];
		    Left.URL_Count=CMD_Temp[3];
		    Right.URL_Count=CMD_Temp[4];
		

		    memcpy(&ALLData.Default2,&Default,17);
		    memcpy(&ALLData.Normal2,&Normal,17);
		    memcpy(&ALLData.Left2,&Left,17);
		    memcpy(&ALLData.Right2,&Right,17);
		    
		    Write_Data_flash(&ALLData,EEL_ID_ALL_Seting);   //push data to flash

	        break;
		
		
		case 13:    //Profile_Mode
		    Profile.Profile_Mode=CMD_Temp[1];
		    
		    switch(Profile.Profile_Mode){
		        case Mod_Default:
		            memcpy(&RamTemp,&Default,17);

		            memcpy(&Ram_ADV.UID,&Eddystone_UID,48);
		            memcpy(&Ram_ADV.URL,&Eddystone_URL,48);
			    
			    RamADV_Count=Default.Adv_Interval;
			    RamUID_Count=Default.UID_Count;
			    RamURL_Count=Default.URL_Count;
			    RamADV_Interval=Default.Adv_Interval*16;
			    Ram_ADV.UID.adv_param.adv_intv_min=RamADV_Interval;
			    Ram_ADV.UID.adv_param.adv_intv_max=RamADV_Interval;
		        break; 
			    
		        case Mod_Normal:
		            memcpy(&RamTemp,&Normal,17);
			    
			    memcpy(&Ram_ADV.UID,&Eddystone_UID_N_flash,48);
		            memcpy(&Ram_ADV.URL,&Eddystone_URL_N_flash,48);
			    
			    RamADV_Count=Normal.Adv_Interval;
			    RamUID_Count=Normal.UID_Count;
			    RamURL_Count=Normal.URL_Count;
			    RamADV_Interval=Normal.Adv_Interval*16;
			    Ram_ADV.UID.adv_param.adv_intv_min=RamADV_Interval;
			    Ram_ADV.UID.adv_param.adv_intv_max=RamADV_Interval;
		        break; 
			
		        case Mod_Left:
		            memcpy(&RamTemp,&Left,17);
			    
		            memcpy(&Ram_ADV.UID,&Eddystone_UID_L_flash,48);
		            memcpy(&Ram_ADV.URL,&Eddystone_URL_L_flash,48);
			    
			    RamADV_Count=Left.Adv_Interval;
			    RamUID_Count=Left.UID_Count;
			    RamURL_Count=Left.URL_Count;
			    RamADV_Interval=Left.Adv_Interval*16;
			    Ram_ADV.UID.adv_param.adv_intv_min=RamADV_Interval;
			    Ram_ADV.UID.adv_param.adv_intv_max=RamADV_Interval;
		        break; 
			
		        case Mod_Right:
		            memcpy(&RamTemp,&Right,17);
			    
		            memcpy(&Ram_ADV.UID,&Eddystone_UID_R_flash,48);
		            memcpy(&Ram_ADV.URL,&Eddystone_URL_R_flash,48);
			    
			    RamADV_Count=Right.Adv_Interval;
			    RamUID_Count=Right.UID_Count;
			    RamURL_Count=Right.URL_Count;
			    RamADV_Interval=Right.Adv_Interval*16;
			    Ram_ADV.UID.adv_param.adv_intv_min=RamADV_Interval;
			    Ram_ADV.UID.adv_param.adv_intv_max=RamADV_Interval;
		        break; 
		    }

		    APP_Set_RunCmd(APP_Update_Chr_Data);

		/*
	            if(CMD_Temp[1]==1){  //L Count
		        L_Seting_Data.LED_Count=CMD_Temp[2];
			//Write_Data_flash(&L_Seting_Data,EEL_ID_L_Seting);   //push data to flash
		    }else if(CMD_Temp[1]==2){  //R Count 
		        R_Seting_Data.LED_Count=CMD_Temp[2];
		    	//Write_Data_flash(&R_Seting_Data,EEL_ID_R_Seting);   //push data to flash
		    }
		*/
	        break;	
		
		
		case 14:    //LED_On_Off 
	            if(CMD_Temp[1]==1){
			    
			if(CMD_Temp[2]==1){
			    LEDChoose=LEDBlue;
			}else if(CMD_Temp[2]==2){
			    LEDChoose=LEDGree;
			}else if(CMD_Temp[2]==3){
			    LEDChoose=LEDRead;
			}
			
			G1D_Sleep_flag=true;
			LED_Count_Temp=L_Seting_Data.LED_Count;
			APP_Set_RunCmd(APP_LED_ON);
		    }else{
			G1D_Sleep_flag=false;
			RamTemp.HW_Led_Mode=LED_Stop;  //stop LED
			APP_Set_RunCmd(APP_LED_OFF);
		    }

		/*
	            if(CMD_Temp[1]==1){  //L Interval
		        L_Seting_Data.Mod_Time=CMD_Temp[2];
			//Write_Data_flash(&L_Seting_Data,EEL_ID_L_Seting);   //push data to flash
		    }else if(CMD_Temp[1]==2){  //R Interval 
		        R_Seting_Data.Mod_Time=CMD_Temp[2];
		    	//Write_Data_flash(&R_Seting_Data,EEL_ID_R_Seting);   //push data to flash
		    }
		    */
	        break;
		
				
		case 15:    //Seting Group 1
    
		    Normal.Adv_Interval=CMD_Temp[1];
		    Normal.UID_Count=CMD_Temp[2];
		    Normal.URL_Count=CMD_Temp[3];
		    Normal.TLM_Interval=(CMD_Temp[4]<<8)+CMD_Temp[5];

		    Left.Adv_Interval=CMD_Temp[6];
		    Left.UID_Count=CMD_Temp[7];
		    Left.URL_Count=CMD_Temp[8];
		    Left.TLM_Interval=(CMD_Temp[9]<<8)+CMD_Temp[10];
		    
		    Right.Adv_Interval=CMD_Temp[11];
		    Right.UID_Count=CMD_Temp[12];
		    Right.URL_Count=CMD_Temp[13];
		    Right.TLM_Interval=(CMD_Temp[14]<<8)+CMD_Temp[15];
		    
		    memcpy(&ALLData.Default2,&Default,17);
    		    memcpy(&ALLData.Normal2,&Normal,17);
    		    memcpy(&ALLData.Left2,&Left,17);
    		    memcpy(&ALLData.Right2,&Right,17);
		    
		break;
		
		case 16:    //Seting Group2
		
                    if(CMD_Temp[1]&0x01){
                        Normal.TLM_Enable=1;
		    }else{
                        Normal.TLM_Enable=0;    
		    }
		    
                    if(CMD_Temp[1]&0x02){
                        Left.TLM_Enable=1;
		    }else{
                        Left.TLM_Enable=0;    
		    }
		    
                    if(CMD_Temp[1]&0x04){
                        Right.TLM_Enable=1;
		    }else{
                        Right.TLM_Enable=0;    
		    }

                    if(CMD_Temp[1]&0x08){
                        Normal.URL_Enable=1;
		    }else{
                        Normal.URL_Enable=0;    
		    }
		    
                    if(CMD_Temp[1]&0x10){
                        Left.URL_Enable=1;
		    }else{
                        Left.URL_Enable=0;    
		    }
		    
                    if(CMD_Temp[1]&0x20){
                        Right.URL_Enable=1;
		    }else{
                        Right.URL_Enable=0;    
		    }
		    
                    if(CMD_Temp[1]&0x40){
                        Normal.UID_Enable=1;
		    }else{
                        Normal.UID_Enable=0;    
		    }
		    
                    if(CMD_Temp[1]&0x80){
                        Left.UID_Enable=1;
		    }else{
                        Left.UID_Enable=0;    
		    }

		    Right.UID_Enable=CMD_Temp[2];
		    
		    memcpy(&ALLData.Default2,&Default,17);
    		    memcpy(&ALLData.Normal2,&Normal,17);
    		    memcpy(&ALLData.Left2,&Left,17);
    		    memcpy(&ALLData.Right2,&Right,17);

	        break;	

		case 17:     //Seting Group3

                    if(CMD_Temp[1]&0x01){
                        Left.AR_Enable=1;
		    }else{
                        Left.AR_Enable=0;    
		    }
		    
                    if(CMD_Temp[1]&0x02){
                        Right.AR_Enable=1;
		    }else{
                        Right.AR_Enable=0;    
		    }
		    
                    if(CMD_Temp[1]&0x04){
                        Left.BTN_Enable=1;
		    }else{
                        Left.BTN_Enable=0;    
		    }

                    if(CMD_Temp[1]&0x08){
                        Right.BTN_Enable=1;
		    }else{
                        Right.BTN_Enable=0;    
		    }
		    
                    if(CMD_Temp[1]&0x10){
                        Left.BTNL_Enable=1;
		    }else{
                        Left.BTNL_Enable=0;    
		    }
		    
                    if(CMD_Temp[1]&0x20){
                        Right.BTNL_Enable=1;
		    }else{
                        Right.BTNL_Enable=0;    
		    }
		    
		    /* no ok  */
                    if(CMD_Temp[2]&0x01){
                        Left.AR_Profile=Mod_Default;
		    }else if(CMD_Temp[2]&0x02){
                        Left.AR_Profile=Mod_Normal;    
		    }else if(CMD_Temp[2]&0x04){
                        Left.AR_Profile=Mod_Left;    
		    }else if(CMD_Temp[2]&0x08){
                        Left.AR_Profile=Mod_Right;    
		    }
		    
                    if(CMD_Temp[2]&0x10){
                        Right.AR_Profile=Mod_Default;
		    }else if(CMD_Temp[2]&0x20){
                        Right.AR_Profile=Mod_Normal;    
		    }else if(CMD_Temp[2]&0x40){
                        Right.AR_Profile=Mod_Left;    
		    }else if(CMD_Temp[2]&0x80){
                        Right.AR_Profile=Mod_Right;    
		    }
		    
 		    Left.AR_Interval=CMD_Temp[3]<<8;
 		    Left.AR_Interval=CMD_Temp[4];
		    
 		    Right.AR_Interval=CMD_Temp[5]<<8;
 		    Right.AR_Interval=CMD_Temp[6];
		    
		   
                    if(CMD_Temp[7]&0x01){
                        Normal.HW_Led_Mode=LED_Stop;
		    }else if(CMD_Temp[7]&0x02){
                        Normal.HW_Led_Mode=LED_Slow_Flash;    
		    }else if(CMD_Temp[7]&0x04){
                        Normal.HW_Led_Mode=LED_Fast_Flash;    
		    }else if(CMD_Temp[7]&0x08){
                        Normal.HW_Led_Mode=LED_ON;    
		    }
		    
                    if(CMD_Temp[8]&0x01){
                        Left.HW_Led_Mode=LED_Stop;
		    }else if(CMD_Temp[8]&0x02){
                        Left.HW_Led_Mode=LED_Slow_Flash;    
		    }else if(CMD_Temp[8]&0x04){
                        Left.HW_Led_Mode=LED_Fast_Flash;    
		    }else if(CMD_Temp[8]&0x08){
                        Left.HW_Led_Mode=LED_ON;    
		    }
		    
                    if(CMD_Temp[9]&0x01){
                        Right.HW_Led_Mode=LED_Stop;
		    }else if(CMD_Temp[9]&0x02){
                        Right.HW_Led_Mode=LED_Slow_Flash;    
		    }else if(CMD_Temp[9]&0x04){
                        Right.HW_Led_Mode=LED_Fast_Flash;    
		    }else if(CMD_Temp[9]&0x08){
                        Right.HW_Led_Mode=LED_ON;    
		    } 

		    if(CMD_Temp[10]&0x01){
                        Normal.HW_Speaker_Mode=Buzzer_Stop;
		    }else if(CMD_Temp[10]&0x02){
                        Normal.HW_Speaker_Mode=Buzzer_one_sound;    
		    }else if(CMD_Temp[10]&0x04){
                        Normal.HW_Speaker_Mode=Buzzer_two_sound;    
		    }else if(CMD_Temp[10]&0x08){
                        Normal.HW_Speaker_Mode=Buzzer_three_sound;    
		    } 
		    

		    if(CMD_Temp[11]&0x01){
                        Left.HW_Speaker_Mode=Buzzer_Stop;
		    }else if(CMD_Temp[11]&0x02){
                        Left.HW_Speaker_Mode=Buzzer_one_sound;    
		    }else if(CMD_Temp[11]&0x04){
                        Left.HW_Speaker_Mode=Buzzer_two_sound;    
		    }else if(CMD_Temp[11]&0x08){
                        Left.HW_Speaker_Mode=Buzzer_three_sound;    
		    } 
		    

		    if(CMD_Temp[12]&0x01){
                        Right.HW_Speaker_Mode=Buzzer_Stop;
		    }else if(CMD_Temp[12]&0x02){
                        Right.HW_Speaker_Mode=Buzzer_one_sound;    
		    }else if(CMD_Temp[12]&0x04){
                        Right.HW_Speaker_Mode=Buzzer_two_sound;    
		    }else if(CMD_Temp[12]&0x08){
                        Right.HW_Speaker_Mode=Buzzer_three_sound;    
		    }
		    
		    if(CMD_Temp[13]&0x01){
                        Normal.HW_Led_Color=LEDBlue;
		    }else if(CMD_Temp[13]&0x02){
                        Normal.HW_Led_Color=LEDGree;    
		    }else if(CMD_Temp[13]&0x04){
                        Normal.HW_Led_Color=LEDRead;    
		    }else if(CMD_Temp[13]&0x08){
                       // Normal.HW_Led_Color=Buzzer_three_sound;    
		    } 	    

		    if(CMD_Temp[14]&0x01){
                        Left.HW_Led_Color=LEDBlue;
		    }else if(CMD_Temp[14]&0x02){
                        Left.HW_Led_Color=LEDGree;    
		    }else if(CMD_Temp[14]&0x04){
                        Left.HW_Led_Color=LEDRead;    
		    }else if(CMD_Temp[14]&0x08){
                        //Left.HW_Led_Color=Buzzer_three_sound;    
		    }   

		    if(CMD_Temp[15]&0x01){
                        Right.HW_Led_Color=LEDBlue;
		    }else if(CMD_Temp[15]&0x02){
                        Right.HW_Led_Color=LEDGree;    
		    }else if(CMD_Temp[15]&0x04){
                        Right.HW_Led_Color=LEDRead;    
		    }else if(CMD_Temp[15]&0x08){
                        //Right.HW_Led_Color=Buzzer_three_sound;    
		    }     
		    
		    /*
		    Left.HW_Led_Mode=CMD_Temp[6];
		    Right.HW_Led_Mode=CMD_Temp[7];
		    Normal.HW_Speaker_Mode=CMD_Temp[8];
		    Left.HW_Speaker_Mode=CMD_Temp[9];  
		    Right.HW_Speaker_Mode=CMD_Temp[10];
		    */
    		    memcpy(&ALLData.Default2,&Default,17);
    		    memcpy(&ALLData.Normal2,&Normal,17);
    		    memcpy(&ALLData.Left2,&Left,17);
    		    memcpy(&ALLData.Right2,&Right,17);

	        break;	
	    
		/*
		case 18:    //Seting Group4
		
		    Default.BTN_Enable=CMD_Temp[1];
		    Left.BTN_Enable=CMD_Temp[2];
		    Right.BTN_Enable=CMD_Temp[3];
		    
		    Default.HW_Led_Mode=CMD_Temp[4];

		    
		    Default.HW_Led_Color=CMD_Temp[8];
		    Normal.HW_Led_Color=CMD_Temp[9];
		    Left.HW_Led_Color=CMD_Temp[10];
		    Right.HW_Led_Color=CMD_Temp[11];
		    
		    Default.HW_Speaker_Mode=CMD_Temp[12];
		    Normal.HW_Speaker_Mode=CMD_Temp[13];
		    Left.HW_Speaker_Mode=CMD_Temp[14];
		    Right.HW_Speaker_Mode=CMD_Temp[15];
		    
    		    memcpy(&ALLData.Default2,&Default,17);
    		    memcpy(&ALLData.Normal2,&Normal,17);
    		    memcpy(&ALLData.Left2,&Left,17);
    		    memcpy(&ALLData.Right2,&Right,17);
		    
	        break;	
		*/
	    }
	}
	
        break;

    default:
        Printf("unsupported SAMS event: 0x%x\n", event->type);
        break;
    }
}

/* ##### Application Handler ##### */
void app_callback(RBLE_MODE mode)
{
    switch (mode) {
    case RBLE_MODE_ACTIVE:
        if(bd_name_param_flash.namelen!=0){
	    RBLE_GAP_Set_Name( &bd_name_param_flash );
	}else{
            RBLE_GAP_Set_Name( &bd_name_param );	
	}
    
        app_msg_send(APP_MSG_BOOTUP);
        break;

    case RBLE_MODE_INITIALIZE:
    case RBLE_MODE_RESET:
    case RBLE_MODE_SLEEP:
    case RBLE_MODE_ERROR:
        /* do nothing */
        break;

    default:
        Printf("unknown mode: 0x%x\n", mode);
        break;
    }
}

BOOL RBLE_App_Init(void)
{
    struct bd_addr public_addr;     /* Public Device Address */
    RBLE_STATUS status;
    char Hex2ASCII[4]={0};
    uint8_t z=0,x=0;
	

    status = RBLE_Init(&app_callback);
    if (RBLE_OK != status) {
        return FALSE;
    }
		   
    ke_state_set(APP_TASK_ID, APP_RESET_STATE);
    
    Push_Data_to_G1D();
    
   // Write_Data_flash(&Eddystone_URL_R_flash,EEL_ID_LURL);   //push data to flash
    
   // Read_Data_flash(&Eddystone_Temp,EEL_ID_LURL);
   //dataflash_format(DF_MODE_ENFORCED);
    
   
    flash_get_bda(&public_addr);
    for(z=4;z<=5;z++){
        Hex2ASCII[x++]=convertHex2ASCII_HighNibble(public_addr.addr[z]);
	Hex2ASCII[x++]=convertHex2ASCII_LowNibble(public_addr.addr[z]);
    }

    if(bd_name_param_flash.namelen!=0){
	//memcpy(&bd_name_param_flash.name[bd_name_param_flash.namelen],Hex2ASCII,4);
	//bd_name_param_flash.namelen+=4;
      	memcpy(ADV_Data.value,bd_name_param_flash.name,bd_name_param_flash.namelen);	
    }else{
	memcpy(&bd_name_param.name[bd_name_param.namelen-1],Hex2ASCII,4);
	bd_name_param.namelen+=4;
	memcpy(ADV_Data.value,bd_name_param.name,bd_name_param.namelen);	
    }
    R_Seting_Data.Mod_Time=10;
    L_Seting_Data.Mod_Time=10;
    
    R_Seting_Data.LED_Count=3;
    L_Seting_Data.LED_Count=3;
    
    Default.Adv_Interval=10;   //100ms    Default.TLM_Enable=1;
    Default.TLM_Interval=600; //'s
    Default.URL_Enable=5;
    Default.URL_Count=1; //'s
    Default.UID_Enable=1;
    Default.UID_Count=1; //'s
    Default.AR_Enable=1;
    Default.AR_Profile=Mod_Default; //'s
    Default.AR_Interval=15; //'s
    Default.BTN_Enable=1;
    Default.HW_Led_Mode=LED_Slow_Flash;
    Default.HW_Led_Color=LEDGree;
    Default.HW_Speaker_Mode=Buzzer_two_sound;
    
    
    Normal.Adv_Interval=10;   //100ms
    Normal.TLM_Enable=1;
    Normal.TLM_Interval=20; //'s
    Normal.URL_Enable=1;
    Normal.URL_Count=10; //'s
    Normal.UID_Enable=1;
    Normal.UID_Count=5; //'s
    Normal.AR_Enable=1;
    Normal.AR_Profile=Mod_Default; //'s
    Normal.AR_Interval=10; //'s
    Normal.BTN_Enable=1;
    Normal.HW_Led_Mode=LED_ON;
    Normal.HW_Led_Color=LEDBlue;
    Normal.HW_Speaker_Mode=Buzzer_three_sound;

    Left.Adv_Interval=10;   //100ms
    Left.TLM_Enable=1;
    Left.TLM_Interval=50; //'s
    Left.URL_Enable=1;
    Left.URL_Count=50; //'s
    Left.UID_Enable=1;
    Left.UID_Count=50; //'s
    Left.AR_Enable=1;
    Left.AR_Profile=Mod_Default; //'s
    Left.AR_Interval=20; //'s
    Left.BTN_Enable=1;
    Left.HW_Led_Mode=LED_Fast_Flash;
    Left.HW_Led_Color=LEDRead;
    Left.HW_Speaker_Mode=Buzzer_one_sound;
    
    Right.Adv_Interval=10;   //100ms
    Right.TLM_Enable=1;
    Right.TLM_Interval=20; //'s
    Right.URL_Enable=0;
    Right.URL_Count=10; //'s
    Right.UID_Enable=1;
    Right.UID_Count=5; //'s
    Right.AR_Enable=1;
    Right.AR_Profile=Mod_Default; //'s
    Right.AR_Interval=15; //'s
    Right.BTN_Enable=1;
    Right.HW_Led_Mode=LED_Slow_Flash;
    Right.HW_Led_Color=LEDGree;
    Right.HW_Speaker_Mode=Buzzer_two_sound;
    
    
    memcpy(&ALLData.Normal2,&Normal,17);
    memcpy(&ALLData.Default2,&Default,17);
    memcpy(&ALLData.Left2,&Left,17);
    memcpy(&ALLData.Right2,&Right,17);
 //dataflash_format(DF_MODE_ENFORCED);
    
    //Write_Data_flash(&ALLData,EEL_ID_ALL_Seting);   //push data to flash

    
   Read_Data_flash(&ALLDataTemp,EEL_ID_ALL_Seting);
    /*
    memcpy(&Left_ADV.UID,&Eddystone_UID_L_flash,48);
    memcpy(&Left_ADV.URL,&Eddystone_URL_L_flash,48);
    
    Write_Data_flash(&Left_ADV,EEL_ID_LUID);   //push data to flash

    Read_Data_flash(&Temp_ADV,EEL_ID_LUID);
*/


    Profile.Profile_Mode=Mod_Normal;
    
    
    
    
    switch(Profile.Profile_Mode){
        case Mod_Default:
            memcpy(&RamTemp,&Default,16);

            memcpy(&Ram_ADV.UID,&Eddystone_UID,48);
            memcpy(&Ram_ADV.URL,&Eddystone_URL,48);
	    
	    RamADV_Count=Default.Adv_Interval;
	    RamUID_Count=Default.UID_Count;
	    RamURL_Count=Default.URL_Count;
	    RamADV_Interval=Default.Adv_Interval*16;
	    Ram_ADV.UID.adv_param.adv_intv_min=RamADV_Interval;
	    Ram_ADV.UID.adv_param.adv_intv_max=RamADV_Interval;
        break; 
	    
        case Mod_Normal:
            memcpy(&RamTemp,&Normal,16);
	    
	    memcpy(&Ram_ADV.UID,&Eddystone_UID_N_flash,48);
            memcpy(&Ram_ADV.URL,&Eddystone_URL_N_flash,48);
	    
	    RamADV_Count=Normal.Adv_Interval;
	    RamUID_Count=Normal.UID_Count;
	    RamURL_Count=Normal.URL_Count;
	    RamADV_Interval=Normal.Adv_Interval*16;
	    Ram_ADV.UID.adv_param.adv_intv_min=RamADV_Interval;
	    Ram_ADV.UID.adv_param.adv_intv_max=RamADV_Interval;
        break; 
	
        case Mod_Left:
            memcpy(&RamTemp,&Left,16);
	    
            memcpy(&Ram_ADV.UID,&Eddystone_UID_L_flash,48);
            memcpy(&Ram_ADV.URL,&Eddystone_URL_L_flash,48);
	    
	    RamADV_Count=Left.Adv_Interval;
	    RamUID_Count=Left.UID_Count;
	    RamURL_Count=Left.URL_Count;
	    RamADV_Interval=Left.Adv_Interval*16;
	    Ram_ADV.UID.adv_param.adv_intv_min=RamADV_Interval;
	    Ram_ADV.UID.adv_param.adv_intv_max=RamADV_Interval;
        break; 
	
        case Mod_Right:
            memcpy(&RamTemp,&Right,16);
	    
            memcpy(&Ram_ADV.UID,&Eddystone_UID_R_flash,48);
            memcpy(&Ram_ADV.URL,&Eddystone_URL_R_flash,48);
	    
	    RamADV_Count=Right.Adv_Interval;
	    RamUID_Count=Right.UID_Count;
	    RamURL_Count=Right.URL_Count;
	    RamADV_Interval=Right.Adv_Interval*16;
	    Ram_ADV.UID.adv_param.adv_intv_min=RamADV_Interval;
	    Ram_ADV.UID.adv_param.adv_intv_max=RamADV_Interval;
        break; 
    }

    APP_Set_RunCmd(APP_Update_Chr_Data);
    
    
    console_init(false, 0);
    
    Printf("12345");
    

    return TRUE;
}
