/**
 ****************************************************************************************
 *
 * @file    sam.h
 *
 * Copyright(C) 2013-2017 Renesas Electronics Corporation
 *
 * This file is generated by Bluetooth Developer Studio plugin.
 *     BDS Version    : 1.1.3139.0
 *     Script Version : 2.0.1
 *
 ****************************************************************************************
 */
#ifndef __SAM_H__
#define __SAM_H__

#define RBLE_BDS_SVC_BEACON_SERVICE                                       {0x00,0xBB}	/* Service: Beacon service */
#define RBLE_BDS_CHAR_BS_N_UID                                                 {0x01,0xBB}	/* Characteristic: UID */
#define RBLE_BDS_CHAR_BS_L_UID                                                 {0x02,0xBB}	/* Characteristic: UID */
#define RBLE_BDS_CHAR_BS_R_UID                                                 {0x03,0xBB}	/* Characteristic: UID */

#define RBLE_BDS_CHAR_BS_N_URL                                                 {0x04,0xBB}	/* Characteristic: URL */
#define RBLE_BDS_CHAR_BS_L_URL                                                 {0x05,0xBB}	/* Characteristic: URL */
#define RBLE_BDS_CHAR_BS_R_URL                                                 {0x06,0xBB}	/* Characteristic: URL */

#define RBLE_BDS_CHAR_BS_Set1                                                {0x07,0xBB}	/* Characteristic: Status */
#define RBLE_BDS_CHAR_BS_Set2                                                {0x08,0xBB}	/* Characteristic: Status */
#define RBLE_BDS_CHAR_BS_Set3                                                {0x09,0xBB}	/* Characteristic: Status */
#define RBLE_BDS_CHAR_BS_Set4                                                {0x0A,0xBB}	/* Characteristic: Status */


#define RBLE_BDS_CHAR_BS_CMD                                                 {0x0B,0xBB}	/* Characteristic: CMD */

#define RBLE_BDS_SVC_DEVICE_INFORMATION                                   {0x0A,0x18}	/* Service: Device Information */
#define RBLE_BDS_CHAR_DI_MANUFACTURER_NAME_STRING                            {0x29,0x2A}	/* Characteristic: Manufacturer Name String */
#define RBLE_BDS_CHAR_DI_MODEL_NUMBER_STRING                                 {0x24,0x2A}	/* Characteristic: Model Number String */
#define RBLE_BDS_CHAR_DI_SERIAL_NUMBER_STRING                                {0x25,0x2A}	/* Characteristic: Serial Number String */
#define RBLE_BDS_CHAR_DI_HARDWARE_REVISION_STRING                            {0x27,0x2A}	/* Characteristic: Hardware Revision String */
#define RBLE_BDS_CHAR_DI_FIRMWARE_REVISION_STRING                            {0x26,0x2A}	/* Characteristic: Firmware Revision String */
#define RBLE_BDS_CHAR_DI_SOFTWARE_REVISION_STRING                            {0x28,0x2A}	/* Characteristic: Software Revision String */
#define RBLE_BDS_CHAR_DI_SYSTEM_ID                                           {0x23,0x2A}	/* Characteristic: System ID */
#define RBLE_BDS_CHAR_DI_IEEE_11073_20601_REGULATORY_CERTIFICATION_DATA_LIST {0x2A,0x2A}	/* Characteristic: IEEE 11073-20601 Regulatory Certification Data List */
#define RBLE_BDS_CHAR_DI_PNP_ID                                              {0x50,0x2A}	/* Characteristic: PnP ID */


#define NEW_PROFILE_SERVER_CCCD_SIZE         (2)

enum RBLE_ATT_ERR_CUSTOM_CODE_enum {
    RBLE_ATT_ERR_QUEUE_FULL = 0x81,     /* Set_Data queue is full */
};

#endif /* __SAM_H__ */
